### ISSUE TITLE
Footer covering tags on smaller screens

### ISSUE THREAD

**Issue by ghost** [eliasdorneles/spidyquotes#19]
## The problem
On displays with a width less than 992 pixels the footer overlaps the "Top Ten tags" section:

![Footer covering "Top Ten tags"](https://user-images.githubusercontent.com/24425801/67828988-add38300-fa92-11e9-9ea1-f21e5f906243.png)
---
![Semitransparent footer covering "Top Ten tags"](https://user-images.githubusercontent.com/24425801/67828998-b4fa9100-fa92-11e9-9821-52bfa4ed8955.png)

### Increase `margin-bottom`
Increase the `margin-bottom` property on `body` to `120px`.

#### Pros
- No major changes to the html or the css.

#### Cons
- Every time content is added to or removed from the footer `margin-bottom` needs updated.
- 120 pixels was gotten empirically.

### Use flexbox
Add this to `main.css`:

```css
body {
    display: flex;
    flex-direction: column;
    height: 100vh;
}

#content {
    flex: 1;
}

.footer {
    flex-shrink: 0;
    background-color: #f5f5f5;
}
```

then add the `id="content"` attribute to `base.html`:

```html
<div id="content" class="container">
...
</div>
<footer class="footer">
...
</footer>
```

#### Pros
- No need to update when the footer changes.

#### Cons
- Not supported by older browsers: [Can I use](https://caniuse.com/#feat=flexbox)
- Requires a minor change to the html.
- Requires a major change to the css.

## Feedback wanted
Any feedback on which solution to use or other possible solutions is appreciated.
